/**
 * landa t3 — one-shot: login (if needed) → list sessions → open console →
 * print / optionally launch T3 against landa (host-first).
 *
 * T3 itself is optional (`npx t3`). Full monorepo vendor comes later;
 * this CLI is the product surface.
 */
import { spawn } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import type { LandaClient } from "./api.js";
import { saveConfig } from "./config.js";
import { ensureLoggedIn } from "./login.js";
import { openSession } from "./open.js";
import { ask } from "./prompt.js";

function openBrowser(url: string): void {
  const plat = process.platform;
  const cmd =
    plat === "darwin" ? "open" : plat === "win32" ? "start" : "xdg-open";
  try {
    spawn(cmd, [url], { detached: true, stdio: "ignore" }).unref();
  } catch {
    /* ignore */
  }
}

export type T3Opts = {
  key?: string;
  base?: string;
  session?: string;
  /** try npx t3 serve */
  serve?: boolean;
  browser?: boolean;
};

export async function runT3(opts: T3Opts = {}): Promise<void> {
  console.log("");
  console.log("landa t3 — host-first sessions + agent harness");
  console.log("");

  const { base, key, client } = await ensureLoggedIn({
    key: opts.key,
    base: opts.base,
  });

  const { sessions } = await client.sessions();
  console.log(`sessions (${sessions.length})  editMode=host-first`);
  if (!sessions.length) {
    console.log("  (none yet)");
  } else {
    for (const s of sessions) {
      console.log(
        `  ${s.status.padEnd(10)} ${s.name.padEnd(22)} ${s.id.slice(0, 8)}…  via=${s.filesVia ?? "?"}`,
      );
    }
  }
  console.log("");

  let sessionId = opts.session;
  if (!sessionId && sessions.length === 1) {
    sessionId = sessions[0]!.id;
    console.log(`→ using only session: ${sessions[0]!.name}`);
  } else if (!sessionId && sessions.length > 1) {
    const pick = await ask("open session (name or id, empty = console only)", {
      default: sessions[0]?.name,
    });
    if (pick) sessionId = pick;
  } else if (!sessionId && sessions.length === 0) {
    const create = await ask("create a session now? [Y/n]", { default: "Y" });
    if (!create || /^y/i.test(create)) {
      const name = await ask("session name", { default: "main" });
      const repo = await ask("git repo URL (optional, enter to skip)");
      const { session } = await client.createSession({
        name: name || "main",
        repo: repo || undefined,
        boot: false,
      });
      sessionId = session.id;
      console.log(`✓ created ${session.name} (${session.status})`);
    }
  }

  const envPath = join(homedir(), ".config", "landa", "t3.env");
  await writeFile(
    envPath,
    [
      `# generated by landa t3 — source this for agent harnesses`,
      `export LANDA_API_BASE='${base}'`,
      `export LANDA_API_KEY='${key}'`,
      sessionId ? `export LANDA_SESSION_ID='${sessionId}'` : "",
      `export LANDA_T3_SYNC=1`,
      `# on alvin only (co-located T3):`,
      `# export LANDA_EXPOSE_VOLUME_PATHS=1`,
      "",
    ]
      .filter(Boolean)
      .join("\n"),
    "utf8",
  );
  await saveConfig({
    apiKey: key,
    apiBase: base,
    ...(sessionId ? { lastSession: sessionId } : {}),
  });

  if (sessionId) {
    await openSession(client, sessionId, {
      browser: opts.browser !== false,
      start: false,
    });
  } else {
    const url = base.replace(/\/$/, "");
    console.log(`→ console ${url}`);
    if (opts.browser !== false) openBrowser(url);
  }

  console.log("env for agents / t3:");
  console.log(`  source ${envPath}`);
  console.log("");
  console.log("T3 (optional agent GUI — not bundled yet):");
  console.log("  # laptop UI only:");
  console.log("  npx t3@latest");
  console.log("  # co-located on alvin (real host volumes + LANDA_T3_SYNC):");
  console.log("  source ~/.config/landa/t3.env");
  console.log("  export LANDA_EXPOSE_VOLUME_PATHS=1   # landa-api process");
  console.log("  npx t3@latest serve");
  console.log("");
  console.log("Next: landa sessions | landa open -r <name> | landa files ls -r <id>");
  console.log("");

  if (opts.serve) {
    await tryServeT3({ base, key, sessionId });
  }
}

async function tryServeT3(opts: {
  base: string;
  key: string;
  sessionId?: string;
}): Promise<void> {
  console.log("→ launching npx t3@latest serve (Ctrl+C to stop)…");
  const env = {
    ...process.env,
    LANDA_API_BASE: opts.base,
    LANDA_API_KEY: opts.key,
    LANDA_T3_SYNC: "1",
    ...(opts.sessionId ? { LANDA_SESSION_ID: opts.sessionId } : {}),
  };
  const child = spawn("npx", ["--yes", "t3@latest", "serve"], {
    stdio: "inherit",
    env,
    shell: process.platform === "win32",
  });
  await new Promise<void>((resolve, reject) => {
    child.on("error", reject);
    child.on("exit", (code) => {
      if (code === 0 || code === null) resolve();
      else reject(new Error(`t3 serve exited ${code}`));
    });
  });
}

/** For open flow when client already known */
export async function printT3Hint(client: LandaClient): Promise<void> {
  void client;
  console.log("tip: landa t3   # login + sessions + console + t3 env");
}
