/**
 * landa t3 — login → session → open console → **launch bundled T3**.
 *
 * Bundle lives at monorepo `t3/` (fork of pingdotgg/t3code, branch landa-native).
 */
import { spawn } from "node:child_process";
import { writeFile, mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { saveConfig } from "./config.js";
import { ensureLoggedIn } from "./login.js";
import { openSession } from "./open.js";
import { ask } from "./prompt.js";
import { bundledT3Root, launchT3 } from "./t3-launch.js";

function openBrowser(url: string): void {
  const plat = process.platform;
  const cmd =
    plat === "darwin" ? "open" : plat === "win32" ? "start" : "xdg-open";
  try {
    spawn(cmd, [url], { detached: true, stdio: "ignore" }).unref();
  } catch {
    /* ignore */
  }
}

export type T3Opts = {
  key?: string;
  base?: string;
  session?: string;
  /** default true — launch T3 after setup */
  launch?: boolean;
  /** legacy: same as launch */
  serve?: boolean;
  browser?: boolean;
  /** start (opens browser) vs serve (headless) */
  mode?: "serve" | "start";
  noLaunch?: boolean;
};

export async function runT3(opts: T3Opts = {}): Promise<void> {
  console.log("");
  console.log("landa t3 — host-first sessions + bundled agent harness");
  console.log(`  t3 bundle: ${bundledT3Root()}`);
  console.log("");

  const { base, key, client } = await ensureLoggedIn({
    key: opts.key,
    base: opts.base,
  });

  const { sessions } = await client.sessions();
  console.log(`sessions (${sessions.length})  editMode=host-first`);
  if (!sessions.length) {
    console.log("  (none yet)");
  } else {
    for (const s of sessions) {
      console.log(
        `  ${s.status.padEnd(10)} ${s.name.padEnd(22)} ${s.id.slice(0, 8)}…  via=${s.filesVia ?? "?"}`,
      );
    }
  }
  console.log("");

  let sessionId = opts.session;
  if (!sessionId && sessions.length === 1) {
    sessionId = sessions[0]!.id;
    console.log(`→ using only session: ${sessions[0]!.name}`);
  } else if (!sessionId && sessions.length > 1) {
    const pick = await ask("open session (name or id, empty = skip)", {
      default: sessions[0]?.name,
    });
    if (pick) sessionId = pick;
  } else if (!sessionId && sessions.length === 0) {
    const create = await ask("create a session now? [Y/n]", { default: "Y" });
    if (!create || /^y/i.test(create)) {
      const name = await ask("session name", { default: "main" });
      const repo = await ask("git repo URL (optional, enter to skip)");
      const { session } = await client.createSession({
        name: name || "main",
        repo: repo || undefined,
        boot: false,
      });
      sessionId = session.id;
      console.log(`✓ created ${session.name} (${session.status})`);
    }
  }

  const configDir = join(homedir(), ".config", "landa");
  await mkdir(configDir, { recursive: true });
  const envPath = join(configDir, "t3.env");
  await writeFile(
    envPath,
    [
      `# generated by landa t3`,
      `export LANDA_API_BASE='${base}'`,
      `export LANDA_API_KEY='${key}'`,
      sessionId ? `export LANDA_SESSION_ID='${sessionId}'` : "",
      `export LANDA_T3_SYNC=1`,
      `# co-located T3 on alvin (real volume paths):`,
      `# export LANDA_EXPOSE_VOLUME_PATHS=1`,
      "",
    ]
      .filter((l) => l !== "")
      .join("\n"),
    "utf8",
  );
  await saveConfig({
    apiKey: key,
    apiBase: base,
    ...(sessionId ? { lastSession: sessionId } : {}),
  });

  if (sessionId) {
    await openSession(client, sessionId, {
      browser: opts.browser !== false,
      start: false,
    });
  } else {
    console.log(`→ console ${base}`);
    if (opts.browser !== false) openBrowser(base.replace(/\/$/, ""));
  }

  console.log(`env: source ${envPath}`);
  console.log("");

  // default: always launch T3 (user request: landa t3 should get t3)
  if (opts.noLaunch === true || opts.launch === false) {
    console.log("skipping T3 launch (--no-launch).");
    return;
  }

  console.log("→ starting T3 Code (bundled)…");
  console.log("  Ctrl+C stops T3 (landa session stays).");
  console.log("");

  await launchT3({
    base,
    key,
    sessionId,
    mode: opts.mode ?? "start",
  });
}
